apiVersion: v1
kind: Secret
metadata:
  name: argocd-deploy-secret
  annotations:
    avp.kubernetes.io/path: {{ .Values.test.secretPath }} 
  labels:
    argocd.argoproj.io/secret-type: repo-creds    
data:
  testKey: <testKey>